// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mcmc_loop_cpp
List mcmc_loop_cpp(NumericVector start_point, int n_sample_points, int burn_in, double covariance_correction, arma::cube env_inv_sigma, arma::vec env_log_norm, arma::mat env_means, double env_threshold, arma::cube sp_inv_sigma, arma::vec sp_log_norm, arma::mat sp_means, double sp_cutoff, double floor_value, arma::vec proposal_mean, arma::mat proposal_cov);
RcppExport SEXP _USE_MCMC_mcmc_loop_cpp(SEXP start_pointSEXP, SEXP n_sample_pointsSEXP, SEXP burn_inSEXP, SEXP covariance_correctionSEXP, SEXP env_inv_sigmaSEXP, SEXP env_log_normSEXP, SEXP env_meansSEXP, SEXP env_thresholdSEXP, SEXP sp_inv_sigmaSEXP, SEXP sp_log_normSEXP, SEXP sp_meansSEXP, SEXP sp_cutoffSEXP, SEXP floor_valueSEXP, SEXP proposal_meanSEXP, SEXP proposal_covSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type start_point(start_pointSEXP);
    Rcpp::traits::input_parameter< int >::type n_sample_points(n_sample_pointsSEXP);
    Rcpp::traits::input_parameter< int >::type burn_in(burn_inSEXP);
    Rcpp::traits::input_parameter< double >::type covariance_correction(covariance_correctionSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type env_inv_sigma(env_inv_sigmaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type env_log_norm(env_log_normSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type env_means(env_meansSEXP);
    Rcpp::traits::input_parameter< double >::type env_threshold(env_thresholdSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type sp_inv_sigma(sp_inv_sigmaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sp_log_norm(sp_log_normSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sp_means(sp_meansSEXP);
    Rcpp::traits::input_parameter< double >::type sp_cutoff(sp_cutoffSEXP);
    Rcpp::traits::input_parameter< double >::type floor_value(floor_valueSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type proposal_mean(proposal_meanSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type proposal_cov(proposal_covSEXP);
    rcpp_result_gen = Rcpp::wrap(mcmc_loop_cpp(start_point, n_sample_points, burn_in, covariance_correction, env_inv_sigma, env_log_norm, env_means, env_threshold, sp_inv_sigma, sp_log_norm, sp_means, sp_cutoff, floor_value, proposal_mean, proposal_cov));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_USE_MCMC_mcmc_loop_cpp", (DL_FUNC) &_USE_MCMC_mcmc_loop_cpp, 15},
    {NULL, NULL, 0}
};

RcppExport void R_init_USE_MCMC(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
