# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mcmc_loop_cpp <- function(start_point, n_sample_points, burn_in, covariance_correction, env_inv_sigma, env_log_norm, env_means, env_threshold, sp_inv_sigma, sp_log_norm, sp_means, sp_cutoff, floor_value, proposal_mean, proposal_cov) {
    .Call(`_USE_MCMC_mcmc_loop_cpp`, start_point, n_sample_points, burn_in, covariance_correction, env_inv_sigma, env_log_norm, env_means, env_threshold, sp_inv_sigma, sp_log_norm, sp_means, sp_cutoff, floor_value, proposal_mean, proposal_cov)
}

